/* Native decoded-block PCM DSP. Configuration and allocation never run in CoreAudio's callback. */
#include "squeezelite.h"
#if DSP
#include <errno.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>

extern log_level loglevel;
#define CHANNELS 2
#define EQ_BANDS 12
#define RAMP_FRAMES 256
#define RESPONSE_POINTS 8192
#define DELAY_LIMIT_MS 100.0
#define TRUE_PEAK_PHASES 4
#define LIMITER_LOOKAHEAD_MS 5.0
#define LIMITER_RELEASE_MS 100.0
#define FIR_PARTITION_FRAMES 512
#define FIR_MAX_TAPS 262144
static const double eq_hz[EQ_BANDS]={31.25,62.5,125,250,500,1000,2000,4000,8000,12000,16000,20000};
typedef enum {F_PEAK,F_NOTCH,F_LOWSHELF,F_HIGHSHELF,F_LOWPASS,F_HIGHPASS} filter_type;
typedef enum {STAGE_EQ,STAGE_PARAMETRIC,STAGE_SPATIAL} filter_stage;
typedef enum {FIR_MAP_STEREO,FIR_MAP_SWAP,FIR_MAP_LEFT,FIR_MAP_RIGHT,FIR_MAP_MONO} fir_map_type;
typedef enum {FIR_LATENCY_PEAK,FIR_LATENCY_START,FIR_LATENCY_CENTER} fir_latency_type;
struct filter_spec{filter_type type;filter_stage stage;double frequency,q,gain_db;bool enabled;};
struct biquad{double b0,b1,b2,a1,a2,z1[CHANNELS],z2[CHANNELS];};
struct complex_value{double real,imag;};
struct chain{
	struct filter_spec spec[DSP_MAX_BIQUADS]; struct biquad filter[DSP_MAX_BIQUADS]; unsigned count,rate;
	double preamp_db,requested_headroom_db,headroom_db,linear_gain,response_peak_db,replaygain_db;
	double balance,width,delay_ms[2],crossfeed,loudness_db,limiter_ceiling_db,limiter_ceiling;
	double crossfeed_alpha,crossfeed_state[2],limiter_gain,limiter_release;
	bool auto_headroom,bypass,eq_bypass,parametric_bypass,fir_bypass,spatial_bypass,limiter_bypass,prepared;
	bool mono,polarity[2],true_peak_enabled,replaygain_headroom,replaygain_managed,fir_normalize;
	double *fir_source[2],*fir[2]; unsigned fir_source_taps,fir_source_rate,fir_taps,fir_latency,fir_max_taps,fir_prepared_rate;
	struct complex_value *fir_partitions[2],*fir_spectra[2],*fir_work; double *fir_input[2],*fir_output[2],*fir_overlap[2];
	unsigned fir_partition_frames,fir_fft_size,fir_partition_count,fir_spectrum_head,fir_block_fill,fir_output_position;
	uint64_t fir_checksum;
	double fir_gain_db,fir_trim_db; fir_map_type fir_map; fir_latency_type fir_latency_mode;
	double *delay[2]; unsigned delay_size,delay_position; double delay_frames[2];
	double true_peak_history[2][16];
	double *limiter_delay[2]; unsigned limiter_position,limiter_size;
	unsigned loudness_low,loudness_high; double loudness_applied_db;
};
static struct{struct chain *current,*retiring,*volatile pending;unsigned rate,ramp_position;volatile u32_t runtime_replay_gain,runtime_volume;bool configured,stream_active,replaygain_managed,replaygain_headroom;struct dsp_telemetry telemetry;}d;
static char dsp_watch_path[PATH_MAX];
static bool dsp_watch_started;
static thread_type dsp_watch_thread;
static double _sinc(double x);

static char *_trim(char*s){char*e;while(*s&&strchr(" \t\r\n",*s))s++;e=s+strlen(s);while(e>s&&strchr(" \t\r\n",e[-1]))*--e='\0';return s;}
static bool _number(const char*s,double*v){char*e;if(!s)return false;errno=0;*v=strtod(s,&e);return *s&&!errno&&!*e&&isfinite(*v);}
static bool _boolean(const char*s,bool*v){if(!strcmp(s,"true")||!strcmp(s,"on")||!strcmp(s,"1")){*v=true;return true;}if(!strcmp(s,"false")||!strcmp(s,"off")||!strcmp(s,"0")){*v=false;return true;}return false;}
static void _free_chain(struct chain*c){unsigned ch;if(!c)return;free(c->fir_source[0]);free(c->fir_source[1]);free(c->fir[0]);free(c->fir[1]);for(ch=0;ch<2;ch++){free(c->fir_partitions[ch]);free(c->fir_spectra[ch]);free(c->fir_input[ch]);free(c->fir_output[ch]);free(c->fir_overlap[ch]);}free(c->fir_work);free(c->delay[0]);free(c->delay[1]);free(c->limiter_delay[0]);free(c->limiter_delay[1]);free(c);}
static bool _add(struct chain*c,filter_type t,filter_stage stage,double f,double q,double g,bool enabled){struct filter_spec*s;if(c->count==DSP_MAX_BIQUADS||!isfinite(f)||!isfinite(q)||!isfinite(g)||f<=0||q<.05||q>50||g< -24||g>24)return false;s=&c->spec[c->count++];s->type=t;s->stage=stage;s->frequency=f;s->q=q;s->gain_db=g;s->enabled=enabled;return true;}
static bool _filter(struct chain*c,const char*v,filter_type t,bool gain){double f,q,g=0;char state[8]="on",tail;int n=gain?sscanf(v,"%lf:%lf:%lf:%7[^:]%c",&f,&q,&g,state,&tail):sscanf(v,"%lf:%lf:%7[^:]%c",&f,&q,state,&tail);int minimum=gain?3:2;bool enabled;if(n<minimum||n>minimum+1||!_boolean(state,&enabled))return false;return _add(c,t,STAGE_PARAMETRIC,f,q,g,enabled);}
static bool _eq(struct chain*c,const char*v){char*copy=strdup(v),*save=NULL,*p;unsigned i=0;if(!copy)return false;for(p=strtok_r(copy,",",&save);p;p=strtok_r(NULL,",",&save)){double g;if(i==EQ_BANDS||!_number(_trim(p),&g)||!_add(c,F_PEAK,STAGE_EQ,eq_hz[i],1.41421356237,g,true)){free(copy);return false;}i++;}free(copy);return i==EQ_BANDS;}
static bool _eq_enabled(struct chain*c,const char*v){char*copy=strdup(v),*save=NULL,*p;unsigned i=0;if(!copy||c->count<EQ_BANDS){free(copy);return false;}for(p=strtok_r(copy,",",&save);p;p=strtok_r(NULL,",",&save)){bool enabled;if(i==EQ_BANDS||!_boolean(_trim(p),&enabled)){free(copy);return false;}c->spec[i++].enabled=enabled;}free(copy);return i==EQ_BANDS;}
static void _normalize(struct biquad*b,double a0){b->b0/=a0;b->b1/=a0;b->b2/=a0;b->a1/=a0;b->a2/=a0;b->z1[0]=b->z1[1]=b->z2[0]=b->z2[1]=0;}
static bool _design(struct biquad*b,const struct filter_spec*s,unsigned rate){double w,cw,sw,alpha,a,a0;if(!s->enabled||((s->type==F_PEAK||s->type==F_LOWSHELF||s->type==F_HIGHSHELF)&&fabs(s->gain_db)<DBL_EPSILON)){memset(b,0,sizeof(*b));b->b0=1;return true;}if(s->frequency>=rate*.495)return false;w=2*M_PI*s->frequency/rate;cw=cos(w);sw=sin(w);alpha=sw/(2*s->q);a=pow(10,s->gain_db/40);switch(s->type){
	case F_PEAK:b->b0=1+alpha*a;b->b1=-2*cw;b->b2=1-alpha*a;a0=1+alpha/a;b->a1=-2*cw;b->a2=1-alpha/a;break;
	case F_NOTCH:b->b0=1;b->b1=-2*cw;b->b2=1;a0=1+alpha;b->a1=-2*cw;b->a2=1-alpha;break;
	case F_LOWPASS:b->b0=(1-cw)/2;b->b1=1-cw;b->b2=(1-cw)/2;a0=1+alpha;b->a1=-2*cw;b->a2=1-alpha;break;
	case F_HIGHPASS:b->b0=(1+cw)/2;b->b1=-(1+cw);b->b2=(1+cw)/2;a0=1+alpha;b->a1=-2*cw;b->a2=1-alpha;break;
	case F_LOWSHELF:{double x=2*sqrt(a)*alpha;b->b0=a*((a+1)-(a-1)*cw+x);b->b1=2*a*((a-1)-(a+1)*cw);b->b2=a*((a+1)-(a-1)*cw-x);a0=(a+1)+(a-1)*cw+x;b->a1=-2*((a-1)+(a+1)*cw);b->a2=(a+1)+(a-1)*cw-x;break;}
	case F_HIGHSHELF:{double x=2*sqrt(a)*alpha;b->b0=a*((a+1)+(a-1)*cw+x);b->b1=-2*a*((a-1)+(a+1)*cw);b->b2=a*((a+1)+(a-1)*cw-x);a0=(a+1)-(a-1)*cw+x;b->a1=2*((a-1)-(a+1)*cw);b->a2=(a+1)-(a-1)*cw-x;break;}
	default:return false;}_normalize(b,a0);return true;}
static bool _filter_active(const struct chain*c,unsigned i){return c->spec[i].enabled&&!((c->spec[i].stage==STAGE_EQ&&c->eq_bypass)||(c->spec[i].stage==STAGE_PARAMETRIC&&c->parametric_bypass)||(c->spec[i].stage==STAGE_SPATIAL&&c->spatial_bypass));}
static void _response(const struct chain*c,double f,double*mag_db,double*phase){unsigned i,ch;double w=2*M_PI*f/c->rate,m=c->preamp_db+c->replaygain_db,p=0;for(i=0;i<c->count;i++)if(_filter_active(c,i)){const struct biquad*b=&c->filter[i];double cr=cos(w),ci=-sin(w),c2r=cos(2*w),c2i=-sin(2*w),nr=b->b0+b->b1*cr+b->b2*c2r,ni=b->b1*ci+b->b2*c2i,dr=1+b->a1*cr+b->a2*c2r,di=b->a1*ci+b->a2*c2i,mag2=(nr*nr+ni*ni)/(dr*dr+di*di);if(mag2>0&&isfinite(mag2)){m+=10*log10(mag2);p+=atan2(ni,nr)-atan2(di,dr);}}if(c->fir_taps&&!c->fir_bypass){double worst=0,left_phase=0;for(ch=0;ch<2;ch++){double real=0,imag=0;for(i=0;i<c->fir_taps;i++){real+=c->fir[ch][i]*cos(w*i);imag-=c->fir[ch][i]*sin(w*i);}if(hypot(real,imag)>worst)worst=hypot(real,imag);if(ch==0)left_phase=atan2(imag,real);}if(worst>0){m+=20*log10(worst);p+=left_phase;}}*mag_db=m;*phase=p*180/M_PI;}
static double _peak(const struct chain*c){unsigned p,points=c->fir_taps?2048:RESPONSE_POINTS;double peak=-INFINITY;for(p=0;p<points;p++){double f=5*pow(c->rate*.495/5.0,(double)p/(points-1)),m,phase;_response(c,f,&m,&phase);if(m>peak)peak=m;}return fmax(0,peak);}
static void _fft(struct complex_value*a,unsigned n,bool inverse){unsigned i,j,len;for(i=1,j=0;i<n;i++){unsigned bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){struct complex_value t=a[i];a[i]=a[j];a[j]=t;}}for(len=2;len<=n;len<<=1){double angle=(inverse?2:-2)*M_PI/len,wr0=cos(angle),wi0=sin(angle);unsigned half=len>>1,start;for(start=0;start<n;start+=len){double wr=1,wi=0;for(j=0;j<half;j++){struct complex_value u=a[start+j],v=a[start+j+half];double vr=v.real*wr-v.imag*wi,vi=v.real*wi+v.imag*wr,next_wr=wr*wr0-wi*wi0;wi=wr*wi0+wi*wr0;wr=next_wr;a[start+j].real=u.real+vr;a[start+j].imag=u.imag+vi;a[start+j+half].real=u.real-vr;a[start+j+half].imag=u.imag-vi;}}}if(inverse)for(i=0;i<n;i++){a[i].real/=n;a[i].imag/=n;}}
static uint64_t _fir_identity(const struct chain*c,unsigned taps,unsigned rate){uint64_t hash=UINT64_C(1469598103934665603);unsigned ch,i;for(ch=0;ch<2;ch++)for(i=0;i<taps;i++){uint64_t bits;memcpy(&bits,&c->fir[ch][i],sizeof(bits));hash^=bits;hash*=UINT64_C(1099511628211);}hash^=rate;hash*=UINT64_C(1099511628211);hash^=(uint64_t)c->fir_map<<8|(uint64_t)c->fir_latency_mode;hash*=UINT64_C(1099511628211);return hash;}
static void _free_fir_engine(struct chain*c){unsigned ch;for(ch=0;ch<2;ch++){free(c->fir_partitions[ch]);c->fir_partitions[ch]=NULL;free(c->fir_spectra[ch]);c->fir_spectra[ch]=NULL;free(c->fir_input[ch]);c->fir_input[ch]=NULL;free(c->fir_output[ch]);c->fir_output[ch]=NULL;free(c->fir_overlap[ch]);c->fir_overlap[ch]=NULL;}free(c->fir_work);c->fir_work=NULL;c->fir_partition_count=c->fir_block_fill=c->fir_output_position=c->fir_spectrum_head=c->fir_prepared_rate=0;}
static bool _prepare_fir(struct chain*c,unsigned rate){unsigned i,ch,taps,peak_index=0,partition;double peak=0,source_peak=0,ratio,normalization=1;if(!c->fir_source_taps||c->fir_bypass)return true;if(c->fir_prepared_rate==rate&&c->fir_taps&&c->fir_partitions[0])return true;_free_fir_engine(c);for(ch=0;ch<2;ch++)for(i=0;i<c->fir_source_taps;i++)if(fabs(c->fir_source[ch][i])>source_peak)source_peak=fabs(c->fir_source[ch][i]);if(c->fir_normalize&&source_peak>0)normalization=1/source_peak;ratio=(double)rate/c->fir_source_rate;taps=(unsigned)ceil(c->fir_source_taps*ratio);if(!taps||taps>c->fir_max_taps)return false;for(ch=0;ch<2;ch++){double*coeff=calloc(taps,sizeof(*coeff));if(!coeff)return false;for(i=0;i<taps;i++){double source=(double)i/ratio,sum=0,weight=0;int center=(int)floor(source),j;for(j=center-31;j<=center+32;j++)if(j>=0&&(unsigned)j<c->fir_source_taps){double distance=source-j,window=fabs(distance)<32?.5+.5*cos(M_PI*distance/32):0,kernel=_sinc(distance)*window;sum+=c->fir_source[ch][j]*kernel;weight+=kernel;}coeff[i]=(weight?sum/weight:0)/ratio*normalization*pow(10,c->fir_gain_db/20);}free(c->fir[ch]);c->fir[ch]=coeff;}
	for(i=0;i<taps;i++){double left=c->fir[0][i],right=c->fir[1][i];if(c->fir_map==FIR_MAP_SWAP){c->fir[0][i]=right;c->fir[1][i]=left;}else if(c->fir_map==FIR_MAP_LEFT)c->fir[1][i]=left;else if(c->fir_map==FIR_MAP_RIGHT)c->fir[0][i]=right;else if(c->fir_map==FIR_MAP_MONO)c->fir[0][i]=c->fir[1][i]=(left+right)*.5;}
	for(i=0;i<taps;i++){double value=fmax(fabs(c->fir[0][i]),fabs(c->fir[1][i]));if(value>peak){peak=value;peak_index=i;}}if(c->fir_trim_db<0&&peak>0){double threshold=peak*pow(10,c->fir_trim_db/20);while(taps>1&&fmax(fabs(c->fir[0][taps-1]),fabs(c->fir[1][taps-1]))<threshold)taps--;if(peak_index>=taps)peak_index=taps-1;}c->fir_taps=taps;c->fir_partition_frames=FIR_PARTITION_FRAMES;c->fir_fft_size=FIR_PARTITION_FRAMES*2;c->fir_partition_count=(taps+FIR_PARTITION_FRAMES-1)/FIR_PARTITION_FRAMES;if(c->fir_latency_mode==FIR_LATENCY_START)c->fir_latency=FIR_PARTITION_FRAMES;else if(c->fir_latency_mode==FIR_LATENCY_CENTER)c->fir_latency=FIR_PARTITION_FRAMES+(taps-1)/2;else c->fir_latency=FIR_PARTITION_FRAMES+peak_index;c->fir_checksum=_fir_identity(c,taps,rate);c->fir_work=calloc(c->fir_fft_size,sizeof(*c->fir_work));if(!c->fir_work)return false;for(ch=0;ch<2;ch++){size_t spectra=(size_t)c->fir_partition_count*c->fir_fft_size;c->fir_partitions[ch]=calloc(spectra,sizeof(*c->fir_partitions[ch]));c->fir_spectra[ch]=calloc(spectra,sizeof(*c->fir_spectra[ch]));c->fir_input[ch]=calloc(c->fir_partition_frames,sizeof(double));c->fir_output[ch]=calloc(c->fir_partition_frames,sizeof(double));c->fir_overlap[ch]=calloc(c->fir_partition_frames,sizeof(double));if(!c->fir_partitions[ch]||!c->fir_spectra[ch]||!c->fir_input[ch]||!c->fir_output[ch]||!c->fir_overlap[ch])return false;for(partition=0;partition<c->fir_partition_count;partition++){struct complex_value*frequency=c->fir_partitions[ch]+(size_t)partition*c->fir_fft_size;unsigned offset=partition*c->fir_partition_frames,count=taps-offset;if(count>c->fir_partition_frames)count=c->fir_partition_frames;for(i=0;i<count;i++)frequency[i].real=c->fir[ch][offset+i];_fft(frequency,c->fir_fft_size,false);}}c->fir_prepared_rate=rate;return true;}
static bool _prepare_delay(struct chain*c,unsigned rate){unsigned size=(unsigned)ceil(DELAY_LIMIT_MS*rate/1000)+2,ch;c->delay_frames[0]=c->delay_ms[0]*rate/1000;c->delay_frames[1]=c->delay_ms[1]*rate/1000;if(c->spatial_bypass||(!c->delay_frames[0]&&!c->delay_frames[1]))return true;for(ch=0;ch<2;ch++){double*line=calloc(size,sizeof(*line));if(!line)return false;free(c->delay[ch]);c->delay[ch]=line;}c->delay_size=size;c->delay_position=0;return true;}
static bool _prepare(struct chain*c,unsigned rate){unsigned i;if(!rate)return true;if(c->prepared&&c->rate==rate)return true;c->prepared=false;c->rate=rate;c->crossfeed_state[0]=c->crossfeed_state[1]=0;c->crossfeed_alpha=1-exp(-2*M_PI*700/rate);for(i=0;i<c->count;i++)if(!_design(&c->filter[i],&c->spec[i],rate))return false;if(!_prepare_fir(c,rate)||!_prepare_delay(c,rate))return false;c->response_peak_db=_peak(c);if(!c->spatial_bypass&&c->width>1)c->response_peak_db+=20*log10(c->width);c->headroom_db=c->auto_headroom?c->response_peak_db+(c->true_peak_enabled?.2:0):c->requested_headroom_db;if(c->replaygain_headroom&&c->replaygain_db>0)c->headroom_db+=c->replaygain_db;c->linear_gain=pow(10,(c->preamp_db+c->replaygain_db-c->headroom_db)/20);c->limiter_ceiling=pow(10,c->limiter_ceiling_db/20);c->limiter_gain=1;c->limiter_release=1-exp(-1.0/(LIMITER_RELEASE_MS*.001*rate));if(!c->limiter_bypass){unsigned ch;c->limiter_size=(unsigned)ceil(LIMITER_LOOKAHEAD_MS*.001*rate);if(c->limiter_size<8)c->limiter_size=8;for(ch=0;ch<2;ch++){free(c->limiter_delay[ch]);c->limiter_delay[ch]=calloc(c->limiter_size,sizeof(double));if(!c->limiter_delay[ch])return false;}}c->prepared=true;return true;}
static bool _range(const char*v,double*out,double minimum,double maximum){return _number(v,out)&&*out>=minimum&&*out<=maximum;}
static bool _fir(struct chain*c,const char*path){double*l=NULL,*r=NULL;unsigned taps=0,rate=0;char error[160];if(!*path)return false;if(!dsp_ir_load(path,&l,&r,&taps,&rate,error,sizeof(error))){LOG_ERROR("unable to load FIR '%s': %s",path,error);return false;}free(c->fir_source[0]);free(c->fir_source[1]);c->fir_source[0]=l;c->fir_source[1]=r;c->fir_source_taps=taps;c->fir_source_rate=rate;return true;}
static bool _parse_polarity(struct chain*c,const char*v){c->polarity[0]=c->polarity[1]=false;if(!strcmp(v,"none"))return true;if(!strcmp(v,"left")){c->polarity[0]=true;return true;}if(!strcmp(v,"right")){c->polarity[1]=true;return true;}if(!strcmp(v,"both")){c->polarity[0]=c->polarity[1]=true;return true;}return false;}
static bool _parse_crossfeed(const char*v,double*out){if(!strcmp(v,"off")){*out=0;return true;}if(!strcmp(v,"light")){*out=.08;return true;}if(!strcmp(v,"medium")){*out=.16;return true;}if(!strcmp(v,"strong")){*out=.25;return true;}return _range(v,out,0,.35);}
static bool _parse_fir_map(const char*v,fir_map_type*out){if(!strcmp(v,"stereo"))*out=FIR_MAP_STEREO;else if(!strcmp(v,"swap"))*out=FIR_MAP_SWAP;else if(!strcmp(v,"left"))*out=FIR_MAP_LEFT;else if(!strcmp(v,"right"))*out=FIR_MAP_RIGHT;else if(!strcmp(v,"mono"))*out=FIR_MAP_MONO;else return false;return true;}
static bool _parse_fir_latency(const char*v,fir_latency_type*out){if(!strcmp(v,"peak"))*out=FIR_LATENCY_PEAK;else if(!strcmp(v,"start"))*out=FIR_LATENCY_START;else if(!strcmp(v,"center"))*out=FIR_LATENCY_CENTER;else return false;return true;}
static bool _parse_fir_trim(const char*v,double*out){if(!strcmp(v,"off")){*out=0;return true;}return _range(v,out,-180,-20);}
static struct chain *_parse(const char*opt){struct chain*c;char*copy,*save=NULL,*tok;bool ok=true;if(!opt||!*opt)return NULL;c=calloc(1,sizeof(*c));copy=strdup(opt);if(!c||!copy){_free_chain(c);free(copy);return NULL;}c->auto_headroom=true;c->width=1;c->fir_normalize=true;c->fir_max_taps=FIR_MAX_TAPS;c->limiter_bypass=true;c->limiter_ceiling_db=-1;c->loudness_low=c->loudness_high=UINT_MAX;for(tok=strtok_r(copy,";",&save);tok;tok=strtok_r(NULL,";",&save)){char*item=_trim(tok),*eq=strchr(item,'='),*k,*v;if(!eq){ok=false;break;}*eq='\0';k=_trim(item);v=_trim(eq+1);
		if(!strcmp(k,"preamp"))ok=_range(v,&c->preamp_db,-60,24);else if(!strcmp(k,"replaygain"))ok=_range(v,&c->replaygain_db,-30,30);else if(!strcmp(k,"headroom")){if(!strcmp(v,"auto"))c->auto_headroom=true;else{ok=_range(v,&c->requested_headroom_db,0,60);c->auto_headroom=false;}}
		else if(!strcmp(k,"bypass"))ok=_boolean(v,&c->bypass);else if(!strcmp(k,"eq_bypass"))ok=_boolean(v,&c->eq_bypass);else if(!strcmp(k,"parametric_bypass"))ok=_boolean(v,&c->parametric_bypass);else if(!strcmp(k,"fir_bypass"))ok=_boolean(v,&c->fir_bypass);else if(!strcmp(k,"spatial_bypass"))ok=_boolean(v,&c->spatial_bypass);else if(!strcmp(k,"limiter_bypass"))ok=_boolean(v,&c->limiter_bypass);
		else if(!strcmp(k,"eq"))ok=_eq(c,v);else if(!strcmp(k,"eq_enabled"))ok=_eq_enabled(c,v);else if(!strcmp(k,"peak"))ok=_filter(c,v,F_PEAK,true);else if(!strcmp(k,"notch"))ok=_filter(c,v,F_NOTCH,false);else if(!strcmp(k,"lowshelf"))ok=_filter(c,v,F_LOWSHELF,true);else if(!strcmp(k,"highshelf"))ok=_filter(c,v,F_HIGHSHELF,true);else if(!strcmp(k,"lowpass"))ok=_filter(c,v,F_LOWPASS,false);else if(!strcmp(k,"highpass"))ok=_filter(c,v,F_HIGHPASS,false);
		else if(!strcmp(k,"fir"))ok=_fir(c,v);else if(!strcmp(k,"fir_gain"))ok=_range(v,&c->fir_gain_db,-60,24);else if(!strcmp(k,"fir_normalize"))ok=_boolean(v,&c->fir_normalize);else if(!strcmp(k,"fir_max_taps")){double limit;ok=_range(v,&limit,FIR_PARTITION_FRAMES,FIR_MAX_TAPS);if(ok)c->fir_max_taps=(unsigned)limit;}else if(!strcmp(k,"fir_trim"))ok=_parse_fir_trim(v,&c->fir_trim_db);else if(!strcmp(k,"fir_channel_map"))ok=_parse_fir_map(v,&c->fir_map);else if(!strcmp(k,"fir_latency"))ok=_parse_fir_latency(v,&c->fir_latency_mode);else if(!strcmp(k,"balance"))ok=_range(v,&c->balance,-1,1);else if(!strcmp(k,"width"))ok=_range(v,&c->width,0,2);else if(!strcmp(k,"mono"))ok=_boolean(v,&c->mono);else if(!strcmp(k,"polarity"))ok=_parse_polarity(c,v);else if(!strcmp(k,"delay_l_ms"))ok=_range(v,&c->delay_ms[0],0,DELAY_LIMIT_MS);else if(!strcmp(k,"delay_r_ms"))ok=_range(v,&c->delay_ms[1],0,DELAY_LIMIT_MS);else if(!strcmp(k,"crossfeed"))ok=_parse_crossfeed(v,&c->crossfeed);else if(!strcmp(k,"loudness"))ok=_range(v,&c->loudness_db,0,12);else if(!strcmp(k,"true_peak"))ok=_boolean(v,&c->true_peak_enabled);else if(!strcmp(k,"limiter")){bool enabled;ok=_boolean(v,&enabled);c->limiter_bypass=!enabled;}else if(!strcmp(k,"limiter_ceiling"))ok=_range(v,&c->limiter_ceiling_db,-12,0);else if(!strcmp(k,"replaygain_headroom"))ok=_boolean(v,&c->replaygain_headroom);else if(!strcmp(k,"replaygain_managed"))ok=_boolean(v,&c->replaygain_managed);else ok=false;if(!ok)break;}
	free(copy);if(ok&&c->loudness_db>0){c->loudness_low=c->count;ok=_add(c,F_LOWSHELF,STAGE_SPATIAL,90,.707,c->loudness_db,true);c->loudness_high=c->count;ok=ok&&_add(c,F_HIGHSHELF,STAGE_SPATIAL,9000,.707,c->loudness_db*.35,true);}if(!ok||!_prepare(c,d.rate)){_free_chain(c);return NULL;}return c;}

bool dsp_configure(const char*opt){struct chain*n=_parse(opt),*old;if(!n){LOG_ERROR("invalid native DSP configuration");return false;}d.replaygain_managed=n->replaygain_managed;d.replaygain_headroom=n->replaygain_headroom;old=__atomic_exchange_n(&d.pending,n,__ATOMIC_ACQ_REL);_free_chain(old);d.configured=true;return true;}
bool dsp_validate(const char*opt){struct chain*c=_parse(opt);_free_chain(c);return c!=NULL;}
static void *_watch_config(void*unused){time_t modified=0;long modified_ns=-1;off_t modified_size=-1;ino_t modified_inode=0;(void)unused;while(1){struct stat status;if(!stat(dsp_watch_path,&status)){
#if defined(__APPLE__)
		long nanoseconds=status.st_mtimespec.tv_nsec;
#else
		long nanoseconds=status.st_mtim.tv_nsec;
#endif
		if(status.st_mtime!=modified||nanoseconds!=modified_ns||status.st_size!=modified_size||status.st_ino!=modified_inode){char*options;modified=status.st_mtime;modified_ns=nanoseconds;modified_size=status.st_size;modified_inode=status.st_ino;usleep(100000);options=dsp_config_load_options(dsp_watch_path,NULL);if(options){if(dsp_configure(options)){LOG_INFO("native DSP live configuration queued");}else{LOG_WARN("native DSP live configuration rejected");}free(options);}}
	}usleep(250000);}return NULL;}
bool dsp_init(const char*opt){struct chain*p=__atomic_exchange_n(&d.pending,NULL,__ATOMIC_ACQ_REL);char*loaded=NULL,*backup=NULL;const char*path=NULL;bool ok;_free_chain(p);_free_chain(d.current);_free_chain(d.retiring);memset(&d,0,sizeof(d));d.runtime_replay_gain=FIXED_ONE;d.telemetry.peak_dbfs=d.telemetry.true_peak_dbfs=-INFINITY;if(opt&&opt[0]=='@'){path=opt+1;loaded=dsp_config_load_options(path,NULL);if(!loaded){size_t size=strlen(path)+5;backup=malloc(size);if(backup){snprintf(backup,size,"%s.bak",path);loaded=dsp_config_load_options(backup,NULL);}}opt=loaded;}ok=dsp_configure(opt);if(ok&&path&&!dsp_watch_started&&strlen(path)<sizeof(dsp_watch_path)){snprintf(dsp_watch_path,sizeof(dsp_watch_path),"%s",path);if(!pthread_create(&dsp_watch_thread,NULL,_watch_config,NULL)){pthread_detach(dsp_watch_thread);dsp_watch_started=true;}else LOG_WARN("native DSP live configuration monitor unavailable");}free(backup);free(loaded);return ok;}
bool dsp_newstream(unsigned rate){struct chain*p;if(!d.configured||!rate)return false;d.rate=rate;memset(&d.telemetry,0,sizeof(d.telemetry));d.telemetry.peak_dbfs=d.telemetry.true_peak_dbfs=-INFINITY;p=__atomic_exchange_n(&d.pending,NULL,__ATOMIC_ACQ_REL);if(!p){p=d.current;d.current=NULL;}if(!p)return false;if(!_prepare(p,rate)){_free_chain(p);return false;}_free_chain(d.current);_free_chain(d.retiring);d.current=p;d.retiring=NULL;d.ramp_position=RAMP_FRAMES;d.replaygain_managed=p->replaygain_managed;d.replaygain_headroom=p->replaygain_headroom;d.telemetry.applied_gain_db=p->preamp_db+p->replaygain_db-p->headroom_db;d.telemetry.response_peak_db=p->response_peak_db;d.telemetry.replaygain_db=p->replaygain_db;d.telemetry.latency_frames=p->fir_latency+(unsigned)ceil(fmax(p->delay_frames[0],p->delay_frames[1]))+p->limiter_size;d.telemetry.fir_taps=p->fir_taps;d.telemetry.fir_partitions=p->fir_partition_count;d.telemetry.fir_checksum=p->fir_checksum;d.telemetry.sample_rate=rate;d.telemetry.fir_active=p->fir_taps&&!p->fir_bypass;d.telemetry.limiter_active=!p->limiter_bypass;d.stream_active=true;return true;}
static double _biquads(struct chain*c,double x,unsigned ch){unsigned i;for(i=0;i<c->count;i++)if(_filter_active(c,i)){struct biquad*b=&c->filter[i];double y=b->b0*x+b->z1[ch];b->z1[ch]=b->b1*x-b->a1*y+b->z2[ch];b->z2[ch]=b->b2*x-b->a2*y;x=y;}return x;}
static double _fir_sample(struct chain*c,double x,unsigned ch){if(!c->fir_taps||c->fir_bypass)return x;c->fir_input[ch][c->fir_block_fill]=x;return c->fir_output[ch][c->fir_output_position];}
static void _fir_advance(struct chain*c){unsigned ch,i,partition;if(!c->fir_taps||c->fir_bypass)return;c->fir_block_fill++;c->fir_output_position++;if(c->fir_block_fill<c->fir_partition_frames)return;for(ch=0;ch<2;ch++){struct complex_value*new_spectrum=c->fir_spectra[ch]+(size_t)c->fir_spectrum_head*c->fir_fft_size;memset(new_spectrum,0,c->fir_fft_size*sizeof(*new_spectrum));for(i=0;i<c->fir_partition_frames;i++)new_spectrum[i].real=c->fir_input[ch][i];_fft(new_spectrum,c->fir_fft_size,false);memset(c->fir_work,0,c->fir_fft_size*sizeof(*c->fir_work));for(partition=0;partition<c->fir_partition_count;partition++){unsigned spectrum_index=(c->fir_spectrum_head+c->fir_partition_count-partition)%c->fir_partition_count;struct complex_value*x=c->fir_spectra[ch]+(size_t)spectrum_index*c->fir_fft_size,*h=c->fir_partitions[ch]+(size_t)partition*c->fir_fft_size;for(i=0;i<c->fir_fft_size;i++){c->fir_work[i].real+=x[i].real*h[i].real-x[i].imag*h[i].imag;c->fir_work[i].imag+=x[i].real*h[i].imag+x[i].imag*h[i].real;}}_fft(c->fir_work,c->fir_fft_size,true);for(i=0;i<c->fir_partition_frames;i++){c->fir_output[ch][i]=c->fir_work[i].real+c->fir_overlap[ch][i];c->fir_overlap[ch][i]=c->fir_work[i+c->fir_partition_frames].real;}memset(c->fir_input[ch],0,c->fir_partition_frames*sizeof(double));}c->fir_spectrum_head=(c->fir_spectrum_head+1)%c->fir_partition_count;c->fir_block_fill=c->fir_output_position=0;}
static double _delay_sample(struct chain*c,double x,unsigned ch){double read,fraction,a,b;unsigned i0,i1;if(!c->delay_size||!c->delay_frames[ch])return x;c->delay[ch][c->delay_position]=x;read=c->delay_position+c->delay_size-c->delay_frames[ch];while(read>=c->delay_size)read-=c->delay_size;i0=(unsigned)read;i1=(i0+1)%c->delay_size;fraction=read-i0;a=c->delay[ch][i0];b=c->delay[ch][i1];return a+(b-a)*fraction;}
static void _frame(struct chain*c,double in_l,double in_r,double*out_l,double*out_r){double runtime=c&&c->replaygain_managed?(double)__atomic_load_n(&d.runtime_replay_gain,__ATOMIC_RELAXED)/FIXED_ONE:1,l=in_l,r=in_r,mid,side,temp;if(c&&c->replaygain_headroom&&runtime>1)runtime=1;if(!c||c->bypass){*out_l=l;*out_r=r;return;}l=_biquads(c,l*c->linear_gain*runtime,0);r=_biquads(c,r*c->linear_gain*runtime,1);l=_fir_sample(c,l,0);r=_fir_sample(c,r,1);_fir_advance(c);if(!c->spatial_bypass){if(c->mono)l=r=(l+r)*.5;mid=(l+r)*.5;side=(l-r)*.5*c->width;l=mid+side;r=mid-side;if(c->crossfeed){temp=l;c->crossfeed_state[0]+=c->crossfeed_alpha*(r-c->crossfeed_state[0]);c->crossfeed_state[1]+=c->crossfeed_alpha*(temp-c->crossfeed_state[1]);l=(l+c->crossfeed_state[0]*c->crossfeed)/(1+c->crossfeed);r=(r+c->crossfeed_state[1]*c->crossfeed)/(1+c->crossfeed);}if(c->balance<0)r*=1+c->balance;else if(c->balance>0)l*=1-c->balance;l=_delay_sample(c,l,0);r=_delay_sample(c,r,1);if(c->polarity[0])l=-l;if(c->polarity[1])r=-r;}*out_l=l;*out_r=r;}
static double _sinc(double x){return fabs(x)<1e-12?1:sin(M_PI*x)/(M_PI*x);}
static double _true_peak(struct chain*c,double value,unsigned ch){unsigned phase,i;double peak=fabs(value);memmove(&c->true_peak_history[ch][1],&c->true_peak_history[ch][0],15*sizeof(double));c->true_peak_history[ch][0]=value;for(phase=1;phase<TRUE_PEAK_PHASES;phase++){double fraction=(double)phase/TRUE_PEAK_PHASES,v=0,weight=0;for(i=0;i<16;i++){double x=(double)i-7-fraction,w=.5+.5*cos(M_PI*x/8),coefficient=_sinc(x)*w;v+=c->true_peak_history[ch][i]*coefficient;weight+=coefficient;}if(weight!=0)v/=weight;if(fabs(v)>peak)peak=fabs(v);}return peak;}
static void _loudness_update(struct chain*c){u32_t fixed;double volume,attenuation,amount;if(!c||!c->loudness_db||c->loudness_low==UINT_MAX||c->spatial_bypass)return;fixed=__atomic_load_n(&d.runtime_volume,__ATOMIC_RELAXED);volume=fixed?(double)fixed/FIXED_ONE:1;if(volume>1)volume=1;attenuation=volume>0?-20*log10(volume):60;if(attenuation>60)attenuation=60;amount=c->loudness_db*fmin(1,attenuation/40);if(fabs(amount-c->loudness_applied_db)<.05)return;c->spec[c->loudness_low].gain_db=amount;c->spec[c->loudness_high].gain_db=amount*.35;{unsigned indexes[2]={c->loudness_low,c->loudness_high},i;for(i=0;i<2;i++){struct biquad next, *active=&c->filter[indexes[i]];double z1[2]={active->z1[0],active->z1[1]},z2[2]={active->z2[0],active->z2[1]};if(_design(&next,&c->spec[indexes[i]],c->rate)){*active=next;active->z1[0]=z1[0];active->z1[1]=z1[1];active->z2[0]=z2[0];active->z2[1]=z2[1];}}}c->loudness_applied_db=amount;d.telemetry.loudness_compensation_db=amount;}
static void _limit(struct chain*c,double peak,double*l,double*r){double target,delayed_l,delayed_r,reduction;if(!c||c->limiter_bypass||!c->limiter_size)return;delayed_l=c->limiter_delay[0][c->limiter_position];delayed_r=c->limiter_delay[1][c->limiter_position];c->limiter_delay[0][c->limiter_position]=*l;c->limiter_delay[1][c->limiter_position]=*r;c->limiter_position=(c->limiter_position+1)%c->limiter_size;target=peak>c->limiter_ceiling?c->limiter_ceiling/peak:1;if(target<c->limiter_gain){if(c->limiter_gain>.999)d.telemetry.limiter_events++;c->limiter_gain=target;}else c->limiter_gain+=c->limiter_release*(target-c->limiter_gain);*l=delayed_l*c->limiter_gain;*r=delayed_r*c->limiter_gain;reduction=c->limiter_gain>0?-20*log10(c->limiter_gain):120;if(reduction>d.telemetry.limiter_gain_reduction_db)d.telemetry.limiter_gain_reduction_db=reduction;}
void dsp_process(s32_t*samples,frames_t frames){struct chain*n;uint64_t frame;double block_peak=0,block_true_peak=0;if(!d.stream_active||!samples)return;n=__atomic_exchange_n(&d.pending,NULL,__ATOMIC_ACQ_REL);if(n){if(!_prepare(n,d.rate))_free_chain(n);else{_free_chain(d.retiring);d.retiring=d.current;d.current=n;d.ramp_position=0;d.telemetry.config_swaps++;d.telemetry.applied_gain_db=n->preamp_db+n->replaygain_db-n->headroom_db;d.telemetry.response_peak_db=n->response_peak_db;d.telemetry.latency_frames=n->fir_latency+(unsigned)ceil(fmax(n->delay_frames[0],n->delay_frames[1]))+n->limiter_size;d.telemetry.fir_taps=n->fir_taps;d.telemetry.fir_partitions=n->fir_partition_count;d.telemetry.fir_checksum=n->fir_checksum;d.telemetry.fir_active=n->fir_taps&&!n->fir_bypass;}}_loudness_update(d.current);_loudness_update(d.retiring);
	for(frame=0;frame<frames;frame++){double in_l=(double)samples[frame*2]/2147483648.0,in_r=(double)samples[frame*2+1]/2147483648.0,l,r,tp_l,tp_r,linked_peak;_frame(d.current,in_l,in_r,&l,&r);if(d.retiring&&d.ramp_position<RAMP_FRAMES){double old_l,old_r,mix=(double)d.ramp_position/RAMP_FRAMES;_frame(d.retiring,in_l,in_r,&old_l,&old_r);l=old_l+(l-old_l)*mix;r=old_r+(r-old_r)*mix;d.ramp_position++;}tp_l=_true_peak(d.current,l,0);tp_r=_true_peak(d.current,r,1);linked_peak=fmax(tp_l,tp_r);_limit(d.current,linked_peak,&l,&r);if(tp_l>block_true_peak)block_true_peak=tp_l;if(tp_r>block_true_peak)block_true_peak=tp_r;if(fabs(l)>block_peak)block_peak=fabs(l);if(fabs(r)>block_peak)block_peak=fabs(r);if(l>=1){samples[frame*2]=INT32_MAX;d.telemetry.clipped_samples++;}else if(l<=-1){samples[frame*2]=INT32_MIN;d.telemetry.clipped_samples++;}else samples[frame*2]=(s32_t)llround(l*2147483648.0);if(r>=1){samples[frame*2+1]=INT32_MAX;d.telemetry.clipped_samples++;}else if(r<=-1){samples[frame*2+1]=INT32_MIN;d.telemetry.clipped_samples++;}else samples[frame*2+1]=(s32_t)llround(r*2147483648.0);if(d.current->delay_size)d.current->delay_position=(d.current->delay_position+1)%d.current->delay_size;}
	if(d.retiring&&d.ramp_position>=RAMP_FRAMES){_free_chain(d.retiring);d.retiring=NULL;}d.telemetry.frames+=frames;if(block_peak>0){double db=20*log10(block_peak);if(!isfinite(d.telemetry.peak_dbfs)||db>d.telemetry.peak_dbfs)d.telemetry.peak_dbfs=db;}if(block_true_peak>0){double db=20*log10(block_true_peak);if(!isfinite(d.telemetry.true_peak_dbfs)||db>d.telemetry.true_peak_dbfs)d.telemetry.true_peak_dbfs=db;if(block_true_peak>1)d.telemetry.true_peak_overs++;}}
void dsp_flush(void){unsigned i,j;struct chain*c[2]={d.current,d.retiring};for(i=0;i<2;i++)if(c[i]){for(j=0;j<c[i]->count;j++){memset(c[i]->filter[j].z1,0,sizeof(c[i]->filter[j].z1));memset(c[i]->filter[j].z2,0,sizeof(c[i]->filter[j].z2));}for(j=0;j<2;j++){if(c[i]->fir_spectra[j])memset(c[i]->fir_spectra[j],0,(size_t)c[i]->fir_partition_count*c[i]->fir_fft_size*sizeof(struct complex_value));if(c[i]->fir_input[j])memset(c[i]->fir_input[j],0,c[i]->fir_partition_frames*sizeof(double));if(c[i]->fir_output[j])memset(c[i]->fir_output[j],0,c[i]->fir_partition_frames*sizeof(double));if(c[i]->fir_overlap[j])memset(c[i]->fir_overlap[j],0,c[i]->fir_partition_frames*sizeof(double));if(c[i]->delay[j])memset(c[i]->delay[j],0,c[i]->delay_size*sizeof(double));if(c[i]->limiter_delay[j])memset(c[i]->limiter_delay[j],0,c[i]->limiter_size*sizeof(double));}c[i]->fir_block_fill=c[i]->fir_output_position=c[i]->fir_spectrum_head=c[i]->delay_position=c[i]->limiter_position=0;c[i]->limiter_gain=1;memset(c[i]->true_peak_history,0,sizeof(c[i]->true_peak_history));}d.stream_active=false;}
bool dsp_active(void){return d.stream_active;}void dsp_get_telemetry(struct dsp_telemetry*t){if(t)*t=d.telemetry;}
unsigned dsp_latency_frames(void){return d.stream_active?d.telemetry.latency_frames:0;}
void dsp_set_replaygain(u32_t gain_value){__atomic_store_n(&d.runtime_replay_gain,gain_value?gain_value:FIXED_ONE,__ATOMIC_RELAXED);if(gain_value)d.telemetry.replaygain_db=20*log10((double)gain_value/FIXED_ONE);}
void dsp_set_volume(u32_t left,u32_t right){u32_t level=left>right?left:right;__atomic_store_n(&d.runtime_volume,level?level:1,__ATOMIC_RELAXED);}
bool dsp_replaygain_managed(void){return d.replaygain_managed;}
bool dsp_response_json(char*buffer,size_t capacity,unsigned points){unsigned i;size_t used=0;if(!buffer||capacity<3||!d.current||!d.current->rate||points<2||points>1024)return false;buffer[used++]='[';for(i=0;i<points;i++){double f=10*pow(d.current->rate*.49/10.0,(double)i/(points-1)),m,p;int n;_response(d.current,f,&m,&p);n=snprintf(buffer+used,capacity-used,"%s{\"hz\":%.3f,\"db\":%.4f,\"phase\":%.3f}",i?",":"",f,m-d.current->headroom_db,p);if(n<0||(size_t)n>=capacity-used)return false;used+=(size_t)n;}if(used+2>capacity)return false;buffer[used++]=']';buffer[used]='\0';return true;}
#endif
